import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import Link from "next/link"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


     
      <h1 className={styles.title}>Home Page</h1>
      <p className={styles.text}>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero, quidem quaerat? Iusto adipisci dignissimos, numquam quos iste accusantium quaerat, hic exercitationem ipsa non maiores suscipit. Nihil voluptate necessitatibus dolorem ad.</p>
      <p className={styles.text}>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero, quidem quaerat? Iusto adipisci dignissimos, numquam quos iste accusantium quaerat, hic exercitationem ipsa non maiores suscipit. Nihil voluptate necessitatibus dolorem ad.</p>
        <Link href="/soficodes"><a className={styles.btn}>See Soficode Listing</a></Link>
 
    </div>
  )
}
